### PR TITLE
Fix eventbus rule query for non-default eventbus closes #1591

### LINKED ISSUE #1591: Query for non-default eventbus eventbridge rules is querying default eventbus
**Describe the bug**

Running `select * from aws_eventbridge_rule` will return all rules for all eventbuses. However, details such as `event_pattern` are null because the logs show the plugin is querying the `default` eventbus when it should be querying the non-default matching one for the rule.

Example log for rule on non-deault eventbus:
`[ERROR] 1676508541484: aws_eventbridge_rule.getAwsEventBridgeRule: api_error="operation error EventBridge: DescribeRule, https response error StatusCode: 400, RequestID: 3cae4cbe-6f88-493d-9c26-eb75a64252a8, ResourceNotFoundException: Rule EventRuleNameHere does not exist on EventBus default."`

**Steampipe version (`steampipe -v`)**
v0.18.6

**Plugin version (`steampipe plugin list`)**
v0.92.2

**To reproduce**
`select * from aws_eventbridge_rule`

**Expected behavior**
Correct `DescribeRule` for all rules

**Additional context**

### PR DESCRIPTION
**Pull request by brentmitchell25**
# Integration test logs
<details>
  <summary>Logs</summary>

```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>

```
select name, event_pattern from aws_eventbridge_rule where event_bus_name = 'non-default-eventbus-name'

+------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>
| name                                                             | event_pattern                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
+------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>
| TestRuleName                                 | {"detail-type":["detail"],"source":["source"]}                                                                                                                                                                         
```
</details>

### CODE REVIEW

File: aws/table_aws_eventbridge_rule.go [hunk 1]
```diff
@@ -205,9 +205,11 @@ func listAwsEventBridgeRules(ctx context.Context, d *plugin.QueryData, h *plugin
 
 func getAwsEventBridgeRule(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
 
+	var eventbusname string
 	var name string
 	if h.Item != nil {
 		name = *h.Item.(*eventbridge.DescribeRuleOutput).Name
+		eventbusname = *h.Item.(*eventbridge.DescribeRuleOutput).EventBusName
 	} else {
 		name = d.KeyColumnQuals["name"].GetStringValue()
```
Comment (bigdatasourav) [inline aws/table_aws_eventbridge_rule.go:214]:
```suggestion
		name = d.KeyColumnQuals["name"].GetStringValue()
		eventbusname = d.KeyColumnQuals["event_bus_name"].GetStringValue()
```

File: aws/table_aws_eventbridge_rule.go [hunk 2]
```diff
@@ -205,9 +205,11 @@ func listAwsEventBridgeRules(ctx context.Context, d *plugin.QueryData, h *plugin
 
 func getAwsEventBridgeRule(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
 
+	var eventbusname string
```
Comment (bigdatasourav) [inline aws/table_aws_eventbridge_rule.go:208]:
```suggestion
	var name, eventbusname string
```

File: aws/table_aws_eventbridge_rule.go [hunk 3]
```diff
@@ -205,9 +205,11 @@ func listAwsEventBridgeRules(ctx context.Context, d *plugin.QueryData, h *plugin
...
 	var name string
```
Comment (bigdatasourav) [inline aws/table_aws_eventbridge_rule.go:209]:
```suggestion
```

File: aws/table_aws_eventbridge_rule.go [hunk 4]
```diff
@@ -205,9 +205,11 @@ func listAwsEventBridgeRules(ctx context.Context, d *plugin.QueryData, h *plugin
```
Comment (bigdatasourav) [inline aws/table_aws_eventbridge_rule.go:205]: Please update the GetConfig [here](https://github.com/turbot/steampipe-plugin-aws/pull/1590/files#diff-180c08cb9e58397134b803cc26086099aa46ef8cfbdcc02d0bd3f0ec53c90ddbR20) as below -
```
Get: &plugin.GetConfig{
			KeyColumns: plugin.AllColumns([]string{"name", "event_bus_name"}),
			IgnoreConfig: &plugin.IgnoreConfig{
				ShouldIgnoreErrorFunc: shouldIgnoreErrors([]string{"ResourceNotFoundException", "ValidationException"}),
			},
			Hydrate: getAwsEventBridgeRule,
		},
```

**Comment by bigdatasourav** [comment]
@brentmitchell25, Thanks for raising this PR; please look into the above suggested changes and rebase your branch with the latest turbot main branch.

File: aws/table_aws_eventbridge_rule.go [hunk 5]
```diff
@@ -225,7 +227,8 @@ func getAwsEventBridgeRule(ctx context.Context, d *plugin.QueryData, h *plugin.H
 
 	// Build the params
```
Comment (bigdatasourav) [inline aws/table_aws_eventbridge_rule.go:228]:
```suggestion
	// Build the params
	// If you do not provide value for the EventBusName parameter, By Default DescribeRule API, will only look into the default event bus.
```

**Comment by brentmitchell25** [comment]
@bigdatasourav Thanks for the review. I have made suggested fixes. Let me know if you need anything else!

File: aws/table_aws_eventbridge_rule.go [hunk 6]
```diff
@@ -227,8 +230,10 @@ func getAwsEventBridgeRule(ctx context.Context, d *plugin.QueryData, h *plugin.H
 	}
 
 	// Build the params
+	// If you do not provide value for the EventBusName parameter, By Default DescribeRule API, will only look into the default event bus.
```
Comment (cbruno10) [inline aws/table_aws_eventbridge_rule.go:233]:
```suggestion
	// Always provide an event bus name since the default event bus is used if not specified
```

I believe this comment is a bit more descriptive as it includes a bit more info, e.g., we're choosing to always include an event bus name

**Comment by brentmitchell25** [comment]
@cbruno10 No problem. Made the requested changes. Let me know of anything else. Thanks!

**Review by cbruno10 — APPROVED** [review]

**Comment by cbruno10** [comment]
Thanks @brentmitchell25 for the PR and follow-up on the review comments! This fix will be released in a new plugin version later this week.
