### PR TITLE
Fixed aws_cloudwatch_log_group table for the error key column is not globally unique Closes #1975

### LINKED ISSUE #1975: aws_cloudwatch_log_group key column is not globally unique
**Describe the bug**

The key column for the aws_cloudwatch_log_group table is `name`: <https://github.com/turbot/steampipe-plugin-aws/blob/v0.123.0/aws/table_aws_cloudwatch_log_group.go#L23>

However, Amazon CloudWatch Logs log group names are only unique within a specific AWS account and region. Thus, queries that filter on exact log group name fail when the same log group name exists in multiple account-region pairs.

I believe the solution is to make the globally unique resource ARN the key column for the table.

Other CloudWatch Logs resource tables may be affected as well, though I have not tested them. For example: <https://github.com/turbot/steampipe-plugin-aws/blob/v0.123.0/aws/table_aws_cloudwatch_log_stream.go#L29>

**Steampipe version (`steampipe -v`)**

v0.21.0

**Plugin version (`steampipe plugin list`)**

v0.123.0

**To reproduce**

1. Create a CloudWatch Logs log group named "steampipe-test" in us-east-1.
1. Create another log group named "steampipe-test" in us-east-2 in the same AWS account.
1. Query log groups across both regions with a filter on that exact name:

   ```sh
   steampipe query  "SELECT account_id, region, name FROM aws_cloudwatch_log_group WHERE name = 'steampipe-test' ORDER BY account_id ASC, region ASC;"
   ```

1. Observe the following error: `Error: get call returned 2 results - the key column is not globally unique (SQLSTATE HV000)`

**Expected behavior**

The query above no longer results in an error.

**Additional context**

Until this issue is fixed, using `LIKE` instead of exact equality seems to be a workaround:

```sh
steampipe query  "SELECT account_id, region, name FROM aws_cloudwatch_log_group WHERE name LIKE 'steampipe-test' ORDER BY account_id ASC, region ASC;"
```

However, in terms of execution plan, I imagine `LIKE` is less efficient than exact string matching.

Thanks for all your hard work making and supporting this wonderful tool!

### PR DESCRIPTION
**Pull request by ParthaI**
# Integration test logs
<details>
  <summary>Logs</summary>

```

No env file present for the current environment:  staging 
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT undefined

SETUP: tests/aws_cloudwatch_log_group []

PRETEST: tests/aws_cloudwatch_log_group

TEST: tests/aws_cloudwatch_log_group
Running terraform
data.aws_region.alternate: Reading...
data.aws_region.alternate: Read complete after 0s [id=us-east-2]
data.aws_caller_identity.current: Reading...
data.aws_region.primary: Reading...
data.aws_partition.current: Reading...
data.aws_partition.current: Read complete after 0s [id=aws]
data.aws_region.primary: Read complete after 0s [id=us-east-1]
data.aws_caller_identity.current: Read complete after 0s [id=333333333333]
data.null_data_source.resource: Reading...
data.null_data_source.resource: Read complete after 0s [id=static]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_cloudwatch_log_group.named_test_resource will be created
  + resource "aws_cloudwatch_log_group" "named_test_resource" {
      + arn               = (known after apply)
      + id                = (known after apply)
      + name              = "turbottest1235"
      + name_prefix       = (known after apply)
      + retention_in_days = 0
      + skip_destroy      = false
      + tags              = {
          + "name" = "turbottest1235"
        }
      + tags_all          = {
          + "name" = "turbottest1235"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + account_id    = "333333333333"
  + aws_partition = "aws"
  + region_name   = "us-east-1"
  + resource_aka  = (known after apply)
  + resource_name = "turbottest1235"
aws_cloudwatch_log_group.named_test_resource: Creating...
aws_cloudwatch_log_group.named_test_resource: Creation complete after 3s [id=turbottest1235]

Warning: Deprecated

  with data.null_data_source.resource,
  on variables.tf line 44, in data "null_data_source" "resource":
  44: data "null_data_source" "resource" {

The null_data_source was historically used to construct intermediate values
to re-use elsewhere in configuration, the same can now be achieved using
locals

(and one more similar warning elsewhere)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

account_id = "333333333333"
aws_partition = "aws"
region_name = "us-east-1"
resource_aka = "arn:aws:logs:us-east-1:333333333333:log-group:turbottest1235"
resource_name = "turbottest1235"

Running SQL query: test-get-query.sql
Warning: terminal options has been deprecated and will be removed in a future version of Steampipe.
These can now be set in a steampipe workspace.
(/Users/parthas/.steampipe/config/default.spc:34,20-42,2)
[
  {
    "name": "turbottest1235"
  }
]
✔ PASSED

Running SQL query: test-hydrate-query.sql
Warning: terminal options has been deprecated and will be removed in a future version of Steampipe.
These can now be set in a steampipe workspace.
(/Users/parthas/.steampipe/config/default.spc:34,20-42,2)
[
  {
    "tags": {
      "name": "turbottest1235"
    }
  }
]
✔ PASSED

Running SQL query: test-list-call-query.sql
Warning: terminal options has been deprecated and will be removed in a future version of Steampipe.
These can now be set in a steampipe workspace.
(/Users/parthas/.steampipe/config/default.spc:34,20-42,2)
[
  {
    "arn": "arn:aws:logs:us-east-1:333333333333:log-group:turbottest1235:*",
    "metric_filter_count": 0,
    "name": "turbottest1235",
    "retention_in_days": null,
    "stored_bytes": 0
  }
]
✔ PASSED

Running SQL query: test-turbot-query.sql
Warning: terminal options has been deprecated and will be removed in a future version of Steampipe.
These can now be set in a steampipe workspace.
(/Users/parthas/.steampipe/config/default.spc:34,20-42,2)
[
  {
    "account_id": "333333333333",
    "akas": [
      "arn:aws:logs:us-east-1:333333333333:log-group:turbottest1235:*"
    ],
    "partition": "aws",
    "region": "us-east-1",
    "tags": {
      "name": "turbottest1235"
    },
    "title": "turbottest1235"
  }
]
✔ PASSED

POSTTEST: tests/aws_cloudwatch_log_group

TEARDOWN: tests/aws_cloudwatch_log_group

SUMMARY:

1/1 passed.

```
</details>

# Example query results
<details>
  <summary>Results</summary>

```
> select * from aws_aab.aws_cloudwatch_log_group where name = 'test'
+------+------------------------------------------------------+---------------------------+------------+---------------------+-------------------+--------------+----------------------------------------------------------------------------------------------+------------->
| name | arn                                                  | creation_time             | kms_key_id | metric_filter_count | retention_in_days | stored_bytes | data_protection                                                                              | data_protect>
+------+------------------------------------------------------+---------------------------+------------+---------------------+-------------------+--------------+----------------------------------------------------------------------------------------------+------------->
| test | arn:aws:logs:us-east-1:333333333333:log-group:test:* | 2023-11-17T22:34:26+05:30 | <null>     | 0                   | <null>            | 0            | {"LastUpdatedTime":null,"LogGroupIdentifier":null,"PolicyDocument":null,"ResultMetadata":{}} | <null>      >
| test | arn:aws:logs:us-east-2:333333333333:log-group:test:* | 2023-10-09T21:31:24+05:30 | <null>     | 0                   | 3                 | 0            | {"LastUpdatedTime":null,"LogGroupIdentifier":null,"PolicyDocument":null,"ResultMetadata":{}} | <null>      >
+------+------------------------------------------------------+---------------------------+------------+---------------------+-------------------+--------------+----------------------------------------------------------------------------------------------+------------->

Time: 7.8s. Rows fetched: 3. Hydrate calls: 9.

> select * from aws_aab.aws_cloudwatch_log_group where name = 'test' and region = 'us-east-1'
+------+------------------------------------------------------+---------------------------+------------+---------------------+-------------------+--------------+----------------------------------------------------------------------------------------------+------------->
| name | arn                                                  | creation_time             | kms_key_id | metric_filter_count | retention_in_days | stored_bytes | data_protection                                                                              | data_protect>
+------+------------------------------------------------------+---------------------------+------------+---------------------+-------------------+--------------+----------------------------------------------------------------------------------------------+------------->
| test | arn:aws:logs:us-east-1:333333333333:log-group:test:* | 2023-11-17T22:34:26+05:30 | <null>     | 0                   | <null>            | 0            | {"LastUpdatedTime":null,"LogGroupIdentifier":null,"PolicyDocument":null,"ResultMetadata":{}} | <null>      >
+------+------------------------------------------------------+---------------------------+------------+---------------------+-------------------+--------------+----------------------------------------------------------------------------------------------+------------->

Time: 3.3s. Rows fetched: 1. Hydrate calls: 3.
> select * from aws_aab.aws_cloudwatch_log_group where name = 'test' and region = 'us-east-4'
+------+-----+---------------+------------+---------------------+-------------------+--------------+-----------------+------------------------+-------+------+------+-----------+--------+------------+------+
| name | arn | creation_time | kms_key_id | metric_filter_count | retention_in_days | stored_bytes | data_protection | data_protection_policy | title | tags | akas | partition | region | account_id | _ctx |
+------+-----+---------------+------------+---------------------+-------------------+--------------+-----------------+------------------------+-------+------+------+-----------+--------+------------+------+
+------+-----+---------------+------------+---------------------+-------------------+--------------+-----------------+------------------------+-------+------+------+-----------+--------+------------+------+

Time: 93ms.

```
</details>

### CODE REVIEW

**Comment by ParthaI** [comment]
Hi @bryanburke,  I anticipate this fix will resolve the issue. I've tested the code changes with the following test cases, including creating two Log Groups with the same name in different regions within an account.

 **Case 1: By providing `name` value in where clause (Returned two results without any error)**

```
> select * from aws_aab.aws_cloudwatch_log_group where name = 'test'
+------+------------------------------------------------------+---------------------------+------------+---------------------+-------------------+--------------+----------------------------------------------------------------------------------------------+------------->
| name | arn                                                  | creation_time             | kms_key_id | metric_filter_count | retention_in_days | stored_bytes | data_protection                                                                              | data_protect>
+------+------------------------------------------------------+---------------------------+------------+---------------------+-------------------+--------------+----------------------------------------------------------------------------------------------+------------->
| test | arn:aws:logs:us-east-1:333333333333:log-group:test:* | 2023-11-17T22:34:26+05:30 | <null>     | 0                   | <null>            | 0            | {"LastUpdatedTime":null,"LogGroupIdentifier":null,"PolicyDocument":null,"ResultMetadata":{}} | <null>      >
| test | arn:aws:logs:us-east-2:333333333333:log-group:test:* | 2023-10-09T21:31:24+05:30 | <null>     | 0                   | 3                 | 0            | {"LastUpdatedTime":null,"LogGroupIdentifier":null,"PolicyDocument":null,"ResultMetadata":{}} | <null>      >
+------+------------------------------------------------------+---------------------------+------------+---------------------+-------------------+--------------+----------------------------------------------------------------------------------------------+------------->

Time: 7.8s. Rows fetched: 3. Hydrate calls: 9.
```

**Case 2: By providing `name` and a valid `region` value in the where clause (Returned one result for a provided region in the where clause)**

```
> select * from aws_aab.aws_cloudwatch_log_group where name = 'test' and region = 'us-east-1'
+------+------------------------------------------------------+---------------------------+------------+---------------------+-------------------+--------------+----------------------------------------------------------------------------------------------+------------->
| name | arn                                                  | creation_time             | kms_key_id | metric_filter_count | retention_in_days | stored_bytes | data_protection                                                                              | data_protect>
+------+------------------------------------------------------+---------------------------+------------+---------------------+-------------------+--------------+----------------------------------------------------------------------------------------------+------------->
| test | arn:aws:logs:us-east-1:333333333333:log-group:test:* | 2023-11-17T22:34:26+05:30 | <null>     | 0                   | <null>            | 0            | {"LastUpdatedTime":null,"LogGroupIdentifier":null,"PolicyDocument":null,"ResultMetadata":{}} | <null>      >
+------+------------------------------------------------------+---------------------------+------------+---------------------+-------------------+--------------+----------------------------------------------------------------------------------------------+------------->

Time: 3.3s. Rows fetched: 1. Hydrate calls: 3.
```

**Case 3: By providing `name` and an invalid `region` value in where clause (Returned empty row)**

```
> select * from aws_aab.aws_cloudwatch_log_group where name = 'test' and region = 'us-east-4'
+------+-----+---------------+------------+---------------------+-------------------+--------------+-----------------+------------------------+-------+------+------+-----------+--------+------------+------+
| name | arn | creation_time | kms_key_id | metric_filter_count | retention_in_days | stored_bytes | data_protection | data_protection_policy | title | tags | akas | partition | region | account_id | _ctx |
+------+-----+---------------+------------+---------------------+-------------------+--------------+-----------------+------------------------+-------+------+------+-----------+--------+------------+------+
+------+-----+---------------+------------+---------------------+-------------------+--------------+-----------------+------------------------+-------+------+------+-----------+--------+------------+------+

Time: 93ms.
```

Could you please give it a try by checking out the PR branch ('issue-1975')? Please let us know if you encounter any other issues.

Steps for checkout

- git clone https://github.com/turbot/steampipe-plugin-aws.git
- cd steampipe-plugin-aws
- git checkout `issue-1975`
- make
- Run steampipe query

Thank you for your interest in Steampipe. We appreciate it!

**Comment by bryanburke** [comment]
@ParthaI I just tested the plugin built from this branch, and the issue is resolved. Thanks!

File: aws/table_aws_cloudwatch_log_group.go [hunk 1]
```diff
@@ -176,19 +189,20 @@ func listCloudwatchLogGroups(ctx context.Context, d *plugin.QueryData, _ *plugin
 //// HYDRATE FUNCTIONS
 
 func getCloudwatchLogGroup(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (interface{}, error) {
+	name := d.EqualsQualString("name")
```
Comment (misraved) [inline aws/table_aws_cloudwatch_log_group.go:192]: @ParthaI shouldn't we be adding an additional check for the `region` column as well?

If a user does not pass in the region along with the name, then we should return `nil`.

**Review by misraved — COMMENTED** [review]
@ParthaI I believe we need to update the table docs to reflect the usage of both the `name` and the `region` column.

Please let me know if you have questions. Thanks!!

File: aws/table_aws_cloudwatch_log_group.go (hunk 1 above)
Comment (ParthaI) [reply aws/table_aws_cloudwatch_log_group.go:192]: @misraved, in accordance with our design, we utilize the [SupportedRegionMatrix](https://github.com/turbot/steampipe-plugin-aws/pull/1976/files#diff-ad2cd4c57b9003b968bc7b23321bcd5cd1e920fd1a51f0bc9e663462126509a9R48). 

Here's how it works:
- If a user queries without specifying the `region` but includes the `name`, we will perform a list API call. This approach ensures that there will be no errors such as 'key column is not globally unique'.
- Conversely, if the `region` value is specified along with the `name`, a Get API call will be executed, but only for the specified `region`.


Note:  We can have multiple LogGroups with same name but in different region. Therefore, our approach ensures that users receive actual results rather than an empty row in such cases.

**Review by misraved — APPROVED** [review]
