### PR TITLE
Fix aws_health_* tables to correctly reference the Global endpoint instead of regional endpoint closes #2449

### LINKED ISSUE #2449: aws_health_* table incorrectly references the regional endpoint
**Describe the bug**
AWS Health is a global service, however in the code it references the regional endpoints. As a result of this when we define anything but `*` in the `regions` config argument, no data is returned

**Steampipe version (`steampipe -v`)**
Example: v1.0.3

**Plugin version (`steampipe plugin list`)**
Example: v1.9.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by misraved**
# Integration test logs
<details>
  <summary>Logs</summary>

```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>

```
Add example SQL query results here (please include the input queries as well)
```
</details>

### CODE REVIEW

**Review by ParthaI — APPROVED** [review]

File: aws/service.go [hunk 1]
```diff
@@ -861,7 +861,7 @@ func GuardDutyClient(ctx context.Context, d *plugin.QueryData) (*guardduty.Clien
 }
 
 func HealthClient(ctx context.Context, d *plugin.QueryData) (*health.Client, error) {
-	cfg, err := getClientForQueryRegion(ctx, d)
+	cfg, err := getClientForDefaultRegion(ctx, d)
```
Comment (pdecat) [inline aws/service.go:864]: I'm still [encountering this issue](https://github.com/turbot/steampipe-plugin-aws/issues/2449#issuecomment-2797326412) with the latest version of the plugin.

Is the default region the right choice here?

Shouldn't it be only one of `us-east-1` or `us-east-2` for main AWS partition,  or `us-gov-west-1` for GovCloud?

https://docs.aws.amazon.com/general/latest/gr/awshealth.html

Comment (pdecat) [reply aws/service.go:864]: Submitted https://github.com/turbot/steampipe-plugin-aws/pull/2470 to fix that.
