### PR TITLE
Populate 'processor_features' Column When Default Value Is Set Closes #2018

### LINKED ISSUE #2018: The aws_rds_db_instance.processor_features column returns null value
**Describe the bug**
Querying RDS instance details, the processor_features column returned by aws_rds_db_instance queries returns only null values.

**Steampipe version (`steampipe -v`)**
v0.21.2

**Plugin version (`steampipe plugin list`)**
v0.123.0

**To reproduce**
Query rds instances with the processor_features column and see is null:
```
> select title, engine, class, processor_features from aws_rds_db_instance;
+------------+------------+----------------+--------------------+
| title      | engine     | class          | processor_features |
+------------+------------+----------------+--------------------+
| ora-a-db01 | oracle-ee  | db.r6i.4xlarge | <null>             |
| ora-a-db02 | oracle-se2 | db.m5.xlarge   | <null>             |
+------------+------------+----------------+--------------------+
```

**Expected behavior**
The processor_features should return json containing the number of cores and threads per core.

Per docs (.instpect aws_rds_db_instance):

> The number of CPU cores and the number of threads per core for the DB instance class of the DB instance.

### PR DESCRIPTION
**Pull request by ParthaI**
Note: This PR contains the fix if the `ProcessorFeatures` value has been set to the default configuration, then we should get the default value for the particular DB Instance.

# Integration test logs
<details>
  <summary>Logs</summary>

```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>

```
> select db_instance_identifier, engine,engine_version, availability_zone, class, processor_features from aws_rds_db_instance;
+------------------------+-----------+------------------------------------+-------------------+--------------+--------------------------------------------------------------------------+
| db_instance_identifier | engine    | engine_version                     | availability_zone | class        | processor_features                                                       |
+------------------------+-----------+------------------------------------+-------------------+--------------+--------------------------------------------------------------------------+
| database-2             | oracle-ee | 19.0.0.0.ru-2023-10.rur-2023-10.r1 | us-east-1b        | db.m5d.large | [{"Name":"threadsPerCore","Value":"2"},{"Name":"coreCount","Value":"1"}] |
| database-1             | mysql     | 8.0.33                             | us-east-1b        | db.t3.micro  | <null>                                                                   |
+------------------------+-----------+------------------------------------+-------------------+--------------+--------------------------------------------------------------------------+

```
</details>

### CODE REVIEW

File: aws/table_aws_rds_db_instance.go [hunk 1]
```diff
@@ -394,6 +394,8 @@ func tableAwsRDSDBInstance(_ context.Context) *plugin.Table {
 				Name:        "processor_features",
 				Description: "The number of CPU cores and the number of threads per core for the DB instance class of the DB instance.",
 				Type:        proto.ColumnType_JSON,
+				Hydrate:     getRDSDBInstanceprocessFeatures,
```
Comment (madhushreeray30) [inline aws/table_aws_rds_db_instance.go:397]:
```suggestion
				Hydrate:     getRDSDBInstanceprocessorFeatures,
```

File: aws/table_aws_rds_db_instance.go [hunk 2]
```diff
@@ -603,6 +605,57 @@ func getRDSDBInstanceCertificate(ctx context.Context, d *plugin.QueryData, h *pl
 	return nil, nil
 }
 
+// DescribeDBInstances API returns the non-default ProcessorFeature value.
+// For populating the default ProcessorFeature value we need to make DescribeOrderableDBInstanceOptions API call.
+func getRDSDBInstanceprocessFeatures(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```
Comment (madhushreeray30) [inline aws/table_aws_rds_db_instance.go:610]:
```suggestion
func getRDSDBInstanceprocessorFeatures(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```

File: aws/table_aws_rds_db_instance.go [hunk 3]
```diff
@@ -603,6 +605,57 @@ func getRDSDBInstanceCertificate(ctx context.Context, d *plugin.QueryData, h *pl
...
+
+	// Return the ProcessFeature details if the
+	if dbInstance.ProcessorFeatures != nil {
+		return dbInstance.ProcessorFeatures, nil
+	}
+
+	// Create service
+	svc, err := RDSClient(ctx, d)
+	if err != nil {
+		plugin.Logger(ctx).Error("aws_rds_db_instance.getRDSDBInstanceprocessFeatures", "connection_error", err)
```
Comment (madhushreeray30) [inline aws/table_aws_rds_db_instance.go:622]:
```suggestion
		plugin.Logger(ctx).Error("aws_rds_db_instance.getRDSDBInstanceprocessorFeatures", "connection_error", err)
```

File: aws/table_aws_rds_db_instance.go [hunk 4]
```diff
@@ -603,6 +605,57 @@ func getRDSDBInstanceCertificate(ctx context.Context, d *plugin.QueryData, h *pl
...
+	params := &rds.DescribeOrderableDBInstanceOptionsInput{
+		Engine:                dbInstance.Engine,
+		EngineVersion:         dbInstance.EngineVersion,
+		DBInstanceClass:       dbInstance.DBInstanceClass,
+		AvailabilityZoneGroup: aws.String(d.EqualsQualString(matrixKeyRegion)),
+	}
+
+	op, err := svc.DescribeOrderableDBInstanceOptions(ctx, params)
+	if err != nil {
+		plugin.Logger(ctx).Error("aws_rds_db_instance.getRDSDBInstanceprocessFeatures", "api_error", err)
```
Comment (madhushreeray30) [inline aws/table_aws_rds_db_instance.go:635]:
```suggestion
		plugin.Logger(ctx).Error("aws_rds_db_instance.getRDSDBInstanceprocessorFeatures", "api_error", err)
```

**Review by madhushreeray30 — COMMENTED** [review]
@ParthaI Please take a look at the comments, thanks!

**Review by madhushreeray30 — APPROVED** [review]
