### PR TITLE
Fixed failed to populate column 'akas' in aws_health_affected_entity, panic runtime error 😱 Closes #2183

### LINKED ISSUE #2183: Failed to populate column 'akas' in aws_health_affected_entity, panic runtime error 😱
**Describe the bug**
When I `select * from aws.aws_health_affected_entity` I get the error:
```
ERROR:  rpc error: code = Unknown desc = aws: failed to populate column 'akas': rpc error: code = Internal desc = transform EnsureStringArray failed with panic runtime error: invalid memory address or nil pointer dereference 
```

**Steampipe version (`steampipe -v`)**
Example: v0.22.2

**Plugin version (`steampipe plugin list`)**
Example: v0.137.0

**To reproduce**
When I `select * from aws.aws_health_affected_entity` I get the error:
```
ERROR:  rpc error: code = Unknown desc = aws: failed to populate column 'akas': rpc error: code = Internal desc = transform EnsureStringArray failed with panic runtime error: invalid memory address or nil pointer dereference 
```

**Expected behavior**
It should return some results, because I have 21 records from `select * from aws.aws_health_event` with lots of open and upcoming events.

**Additional context**
I am querying against an AWS gov-cloud account.

### PR DESCRIPTION
**Pull request by ParthaI**
# Integration test logs
<details>
  <summary>Logs</summary>

```
N/A
```
</details>

# Example query results
<details>
  <summary>Results</summary>

```

```
</details>

### CODE REVIEW

File: aws/table_aws_health_event.go [hunk 1]
```diff
@@ -91,7 +92,7 @@ func tableAwsHealthEvent(_ context.Context) *plugin.Table {
 				Name:        "akas",
 				Description: resourceInterfaceDescription("akas"),
 				Type:        proto.ColumnType_JSON,
-				Transform:   transform.FromField("Arn").Transform(transform.EnsureStringArray),
+				Transform:   transform.FromField("Arn").Transform(getHealthEventAka),
```
Comment (misraved) [inline aws/table_aws_health_event.go:95]: @ParthaI I do not think we need to add the new Transform function here.

File: aws/table_aws_health_event.go [hunk 2]
```diff
@@ -160,6 +161,29 @@ func listHealthEvents(ctx context.Context, d *plugin.QueryData, h *plugin.Hydrat
...
+			}
+			return []string{*v}, nil
+		default:
+			str := fmt.Sprintf("%v", d.Value)
+			return []string{str}, nil
+		}
+
+	}
+	return nil, nil
+}
```
Comment (misraved) [inline aws/table_aws_health_event.go:185]: I don't think this is required either because `event_arn` will never be nil.

**Review by misraved — APPROVED** [review]
