### PR TITLE
Revert handling <root_account> password_enabled check in table_aws_iam_credential_report table.Closes #656

### LINKED ISSUE #656: Handling <root_account> password_enabled check in table_aws_iam_credential_report table.
**Describe the bug**
Refer 
https://github.com/turbot/steampipe-mod-aws-compliance/issues/276

https://github.com/turbot/steampipe-plugin-aws/blob/main/aws/table_aws_iam_credential_report.go#L169
https://github.com/turbot/steampipe-plugin-aws/blob/6d285c058dc23f4a69aac834bde4be80b8deb68f/aws/table_aws_iam_credential_report.go#L251

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by bigdatasourav**
# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
Add example SQL query results here (please include the input queries as well)
```
</details>

### CODE REVIEW

File: aws/table_aws_iam_credential_report.go [hunk 1]
```diff
@@ -251,7 +251,7 @@ func listCredentialReports(ctx context.Context, d *plugin.QueryData, _ *plugin.H
 func passwordEnabledToBool(_ context.Context, d *transform.TransformData) (interface{}, error) {
 	enabled := types.SafeString(d.Value)
 	if enabled == "not_supported" {
-		return false, nil
+		return true, nil
```
Comment (rajlearner17) [inline aws/table_aws_iam_credential_report.go:254]: @bigdatasourav let's add a comment on why we are retaining this `true` condition to help in future.

**Review by rajlearner17 — APPROVED** [review]
LGTM
