### PR TITLE
aws_route53_record results incomplete or broken closes #1374

### LINKED ISSUE #1374: aws_route53_record results incomplete or broken
**Describe the bug**
something changed between 0.71 and the current release where the number of records returned in our production account is vastly different.  and the current 0.8.0 plugin will error out.  



**Steampipe version (`steampipe -v`)**
0.15 - v0.16.1

**Plugin version (`steampipe plugin list`)**
v0.79-v0.80.0


**To reproduce**
Tested this locally
```
1042 ~/.steampipe/config % steampipe plugin list
+---------------------------------------------------+---------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Name                                              | Version | Connections                                                                                                                                                                                                                                                    |
+---------------------------------------------------+---------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| hub.steampipe.io/plugins/turbot/aws@0.79.0        | 0.79.0  | prod                                                                                                                                                                                                                                                           |
| hub.steampipe.io/plugins/turbot/aws@latest        | 0.71.0  | aws,dev3,prod_old                                                                                                                                                                                                                                              |
+---------------------------------------------------+---------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1043 ~/.steampipe/config % steampipe query      
Welcome to Steampipe v0.15.0
For more information, type .help
> select
      count(*)
      
    from
      prod.aws_route53_zone as aws_prodz,
      prod.aws_route53_record as aws_prodr
    where
> select
      count(*)
      
    from
      prod.aws_route53_zone as aws_prodz,
      prod.aws_route53_record as aws_prodr
    where
      aws_prodr.zone_id = aws_prodz.id
+-------+
| count |
+-------+
| 1582  |
+-------+
> select
      count(*)
      
    from
      prod_old.aws_route53_zone as aws_prodz,
      prod_old.aws_route53_record as aws_prodr
    where
      aws_prodr.zone_id = aws_prodz.id
+-------+
| count |
+-------+
| 2989  |
+-------+
> 
```

Testing on our service node
```
+-------------------------------------------------------------------+
|                                                                   |
| A new version of Steampipe is available! 0.16.1 → 0.16.4          |
| You can update by downloading from https://steampipe.io/downloads |
|                                                                   |
+-------------------------------------------------------------------+

+---------------------------------------------------+---------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Name                                              | Version | Connections                                                                                                                                                                                                                                                                                                 |
+---------------------------------------------------+---------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| hub.steampipe.io/plugins/turbot/aws@latest        | 0.80.0  | allaws,.... |
|                                                   |         |                                                                                                                                                                                                        |

+---------------------------------------------------+---------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
steampipe@ip-xxxxxxx:~$ steampipe query
Welcome to Steampipe v0.16.1
For more information, type .help
> select
      count(*)
      
    from
      aws_prod.aws_route53_zone as aws_prodz,
      aws_prod.aws_route53_record as aws_prodr
    where
      aws_prodr.zone_id = aws_prodz.id
Error: operation error Route 53: ListResourceRecordSets, https response error StatusCode: 400, RequestID: 6b156ee5-639f-4369-b106-1a14c8179645, InvalidInput:  (SQLSTATE HV000)
> 
```
**Expected behavior**
All records returned 
 Not sure if https://github.com/turbot/steampipe-plugin-aws/pull/1356 broke it

### PR DESCRIPTION
**Pull request by ParthaI**
# Integration test logs
<details>
  <summary>Logs</summary>

```
No env file present for the current environment:  staging 
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT undefined

SETUP: tests/aws_route53_record []

PRETEST: tests/aws_route53_record

TEST: tests/aws_route53_record
Running terraform
data.aws_region.primary: Reading...
data.aws_caller_identity.current: Reading...
data.aws_partition.current: Reading...
data.aws_region.primary: Read complete after 0s [id=us-east-1]
data.aws_partition.current: Read complete after 0s [id=aws]
data.aws_region.alternate: Reading...
data.aws_region.alternate: Read complete after 0s [id=us-east-2]
data.aws_caller_identity.current: Read complete after 1s [id=546902152798]
data.null_data_source.resource: Reading...
data.null_data_source.resource: Read complete after 0s [id=static]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_eip.named_test_resource will be created
  + resource "aws_eip" "named_test_resource" {
      + allocation_id        = (known after apply)
      + association_id       = (known after apply)
      + carrier_ip           = (known after apply)
      + customer_owned_ip    = (known after apply)
      + domain               = (known after apply)
      + id                   = (known after apply)
      + instance             = (known after apply)
      + network_border_group = (known after apply)
      + network_interface    = (known after apply)
      + private_dns          = (known after apply)
      + private_ip           = (known after apply)
      + public_dns           = (known after apply)
      + public_ip            = (known after apply)
      + public_ipv4_pool     = (known after apply)
      + tags_all             = (known after apply)
      + vpc                  = true
    }

  # aws_route53_record.named_test_resource will be created
  + resource "aws_route53_record" "named_test_resource" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "www.turbottest858.com"
      + records         = (known after apply)
      + set_identifier  = "live"
      + ttl             = 300
      + type            = "A"
      + zone_id         = (known after apply)

      + weighted_routing_policy {
          + weight = 90
        }
    }

  # aws_route53_zone.named_test_resource will be created
  + resource "aws_route53_zone" "named_test_resource" {
      + arn                 = (known after apply)
      + comment             = "Managed by Terraform"
      + force_destroy       = true
      + id                  = (known after apply)
      + name                = "turbottest858.com"
      + name_servers        = (known after apply)
      + primary_name_server = (known after apply)
      + tags_all            = (known after apply)
      + zone_id             = (known after apply)
    }

Plan: 3 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + account_id    = "546902152798"
  + aws_region    = "us-east-1"
  + public_ip     = (known after apply)
  + resource_aka  = (known after apply)
  + resource_name = "turbottest858"
  + zone_id       = (known after apply)
aws_route53_zone.named_test_resource: Creating...
aws_eip.named_test_resource: Creating...
aws_eip.named_test_resource: Creation complete after 1s [id=eipalloc-0e07e2edb3906d9c4]
aws_route53_zone.named_test_resource: Still creating... [10s elapsed]
aws_route53_zone.named_test_resource: Still creating... [20s elapsed]
aws_route53_zone.named_test_resource: Still creating... [30s elapsed]
aws_route53_zone.named_test_resource: Creation complete after 37s [id=Z07244571C5HM5NU19N95]
aws_route53_record.named_test_resource: Creating...
aws_route53_record.named_test_resource: Still creating... [10s elapsed]
aws_route53_record.named_test_resource: Still creating... [20s elapsed]
aws_route53_record.named_test_resource: Still creating... [30s elapsed]
aws_route53_record.named_test_resource: Creation complete after 40s [id=Z07244571C5HM5NU19N95_www.turbottest858.com_A_live]

Warning: Deprecated

  with data.null_data_source.resource,
  on variables.tf line 44, in data "null_data_source" "resource":
  44: data "null_data_source" "resource" {

The null_data_source was historically used to construct intermediate values
to re-use elsewhere in configuration, the same can now be achieved using
locals

(and one more similar warning elsewhere)

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.

Outputs:

account_id = "546902152798"
aws_region = "us-east-1"
public_ip = "3.209.46.168"
resource_aka = "arn:aws:route53:::hostedzone/Z07244571C5HM5NU19N95/recordset/www.turbottest858.com./A/live"
resource_name = "turbottest858"
zone_id = "Z07244571C5HM5NU19N95"

Running SQL query: test-list-query.sql
[
  {
    "name": "www.turbottest858.com.",
    "records": [
      "3.209.46.168"
    ],
    "set_identifier": "live",
    "ttl": "300",
    "type": "A",
    "weight": 90,
    "zone_id": "Z07244571C5HM5NU19N95"
  }
]
✔ PASSED

Running SQL query: test-not-found-query.sql
null
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "akas": [
      "arn:aws:route53:::hostedzone/Z07244571C5HM5NU19N95/recordset/www.turbottest858.com./A/live"
    ],
    "title": "www.turbottest858.com."
  }
]
✔ PASSED

POSTTEST: tests/aws_route53_record

TEARDOWN: tests/aws_route53_record

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>

```
> select
      count(*)
      
    from
      aws_route53_zone as aws_prodz,
      aws_route53_record as aws_prodr
    where
      aws_prodr.zone_id = aws_prodz.id
+-------+
| count |
+-------+
| 1508  |
+-------+

> select
      count(*)
      
    from
      aws_old.aws_route53_zone as aws_prodz,
      aws_old.aws_route53_record as aws_prodr
    where
      aws_prodr.zone_id = aws_prodz.id
+-------+
| count |
+-------+
| 1508  |
+-------+
> select
      count(*)
      
    from
      aws_route53_zone as aws_prodz,
      aws_route53_record as aws_prodr
    where
      aws_prodr.zone_id = aws_prodz.id
+-------+
| count |
+-------+
| 1508  |
+-------+

> select
      count(*)
      
    from
      aws_old.aws_route53_zone as aws_prodz,
      aws_old.aws_route53_record as aws_prodr
    where
      aws_prodr.zone_id = aws_prodz.id
+-------+
| count |
+-------+
| 1508  |
+-------+
```
</details>

### CODE REVIEW

File: aws/table_aws_route53_record.go [hunk 1]
```diff
@@ -180,22 +180,6 @@ func listRoute53Records(ctx context.Context, d *plugin.QueryData, _ *plugin.Hydr
 		}
 
 		for _, record := range op.ResourceRecordSets {
-			// The StartRecordName and StartRecordType input parameters only tell
```
Comment (cbruno10) [inline aws/table_aws_route53_record.go:183]: @ParthaI can you please describe a bit more how the start record name/type matching was causing the bug? Can you please also provide some example inputs/results to demonstrate? Thanks!

**Review by cbruno10 — CHANGES_REQUESTED** [review]
@ParthaI Please see comment, thanks!

File: aws/table_aws_route53_record.go (hunk 1 above)
Comment (ParthaI) [reply aws/table_aws_route53_record.go:183]: @cbruno10 Yes,  the start record name/type matching was causing the bug. As per the API behavior, we must have to pass both the last record name and type, as in the input param, if we are performing the pagination.

[which is already been handled](https://github.com/turbot/steampipe-plugin-aws/pull/1375/files#diff-014c84a973889489a14dc5bfbdf67b1e2670e42393ee40b6dd917cbc90ca5a40L209) post the logic which we removed. The newly added code was not being executed due to `continue` [statement](https://github.com/turbot/steampipe-plugin-aws/pull/1375/files#diff-014c84a973889489a14dc5bfbdf67b1e2670e42393ee40b6dd917cbc90ca5a40L191)

Comment (ParthaI) [reply aws/table_aws_route53_record.go:183]: We made the API call, Initially, there was no record name/type in the input param, so the [newly added code](https://github.com/turbot/steampipe-plugin-aws/pull/1375/files#diff-014c84a973889489a14dc5bfbdf67b1e2670e42393ee40b6dd917cbc90ca5a40L209) was executed properly, and setting the record name/type, while we were fetching the second-page result then the [if condition](https://github.com/turbot/steampipe-plugin-aws/pull/1375/files#diff-014c84a973889489a14dc5bfbdf67b1e2670e42393ee40b6dd917cbc90ca5a40L189) was satisfying and was not letting the below code to be executed, it was resulting the wrong output.

Comment (ParthaI) [reply aws/table_aws_route53_record.go:183]: I was unable not replicate the `InvalidInput` error as per the query mentioned in the issue description, but if we will set the name and type incorrectly, we will get the `InvalidInput` error for that. So added that to ignore config. The removed code resulted in the wrong `count` output.

Comment (cbruno10) [reply aws/table_aws_route53_record.go:183]: Should we ignore the `InvalidInput` error though, since the table code controls how the start record type and name input parameters are used. So ideally, our code should handle how those input parameters are set (based on the query quals) in a way that we never hit the `InvalidInput` error. If we're unable to reproduce a specific scenario that replicates the issue, we should not just add general handling that ignores it, as it really masks the issue.

And can you please elaborate **how** the removed code resulted in the wrong `count` output? It may be my misunderstanding, but I'm still unclear as to how that affects count for queries that don't specify any quals.

File: aws/parliament_iam_permissions.go [hunk 2]
```diff
@@ -35,7 +35,8 @@ type ParliamentService struct {
 
 type ParliamentPermissions []ParliamentService
 
-func getParliamentIamPermissions() ParliamentPermissions {
+func getParliamentIamPermissions() ParliamentPermissions { return ParliamentPermissions{} }
+/*
```
Comment (cbruno10) [inline aws/parliament_iam_permissions.go:39]: @LalitTurbot Can you please remove this?

File: aws/table_aws_route53_record.go [hunk 3]
```diff
@@ -152,26 +152,36 @@ func listRoute53Records(ctx context.Context, d *plugin.QueryData, _ *plugin.Hydr
...
+	// Reduce the basic request limit down if the user has only requested a small number of rows
+	if d.QueryContext.Limit != nil {
+		limit := int32(*d.QueryContext.Limit)
+		if limit < maxItems {
+			if limit < 1 {
+				maxItems = int32(1)
+			} else {
+				maxItems = int32(limit)
+			}
+		}
```
Comment (cbruno10) [inline aws/table_aws_route53_record.go:165]:
```suggestion
		if limit < maxItems {
			maxItems = int32(limit)
		}
```

I don't think we need to check if the limit is less than 1 anymore, as I ran some tests earlier and it seems like if someone runs with a query with `limit 0`, the hydrate functions aren't called.

File: aws/table_aws_route53_record.go [hunk 4]
```diff
@@ -152,26 +152,36 @@ func listRoute53Records(ctx context.Context, d *plugin.QueryData, _ *plugin.Hydr
...
+		// Constraint: Specifying record type without specifying record name returns an InvalidInput error
+		if equalQuals["type"] != nil {
 			input.StartRecordType = route53Types.RRType(equalQuals["type"].GetStringValue())
 		}
 	}
 
-	// Paginator not avilable for the in v2, till date 09/30/2022
-	// Also, API doesn't support paging. Therfore not handling limit for the function
+	// v2 new Paginator is not avilable for the API in SDK as of data.
+	// Instead using generic way to do pagination
```
Comment (cbruno10) [inline aws/table_aws_route53_record.go:184]:
```suggestion
	// Paginator is not in AWS SDK v2 as of 2022/11/04
	// So use generic pagination handling instead
```

**Review by cbruno10 — CHANGES_REQUESTED** [review]
@LalitTurbot Please see comments, thanks!

**Review by cbruno10 — APPROVED** [review]
