### PR TITLE
Fixed aws_ssm_document queries fail when querying multiple regions with the same document name Closes #1715

### LINKED ISSUE #1715: aws_ssm_document queries fail when querying multiple regions with the same document name
**Describe the bug**
If I run `select name from aws_ssm_document where name = 'testdoc'`, and I have a document in each region for my configured regions in `aws.spc`, I receive an error like:
```
Error: get call returned 2 results - the key column is not globally unique (SQLSTATE HV000)
```

**Steampipe version (`steampipe -v`)**
v0.19.4

**Plugin version (`steampipe plugin list`)**
v0.100.0

**To reproduce**
See above.

**Expected behavior**
The get call should return 1 row and not error

**Additional context**

### PR DESCRIPTION
**Pull request by ParthaI**
# Integration test logs
<details>
  <summary>Logs</summary>

```
No env file present for the current environment:  staging 
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT undefined

SETUP: tests/aws_ssm_document []

PRETEST: tests/aws_ssm_document

TEST: tests/aws_ssm_document
Running terraform
data.aws_partition.current: Reading...
data.aws_caller_identity.current: Reading...
data.aws_region.primary: Reading...
data.aws_region.primary: Read complete after 0s [id=us-east-1]
data.aws_partition.current: Read complete after 0s [id=aws]
data.aws_region.alternate: Reading...
data.aws_region.alternate: Read complete after 0s [id=us-east-2]
data.aws_caller_identity.current: Read complete after 2s [id=112233445566]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_ssm_document.named_test_resource will be created
  + resource "aws_ssm_document" "named_test_resource" {
      + arn              = (known after apply)
      + content          = <<-EOT
            schemaVersion: '1.2'
            description: Check ip configuration of a Linux instance.
            parameters: {}
            runtimeConfig:
              'aws:runShellScript':
                properties:
                  - id: '0.aws:runShellScript'
                    runCommand:
                      - ifconfig
        EOT
      + created_date     = (known after apply)
      + default_version  = (known after apply)
      + description      = (known after apply)
      + document_format  = "YAML"
      + document_type    = "Command"
      + document_version = (known after apply)
      + hash             = (known after apply)
      + hash_type        = (known after apply)
      + id               = (known after apply)
      + latest_version   = (known after apply)
      + name             = "turbottest50436"
      + owner            = (known after apply)
      + parameter        = (known after apply)
      + platform_types   = (known after apply)
      + schema_version   = (known after apply)
      + status           = (known after apply)
      + tags             = {
          + "name" = "turbottest50436"
        }
      + tags_all         = {
          + "name" = "turbottest50436"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + aws_partition = "aws"
  + aws_region    = "us-east-1"
  + resource_aka  = (known after apply)
  + resource_name = "turbottest50436"
aws_ssm_document.named_test_resource: Creating...
aws_ssm_document.named_test_resource: Creation complete after 3s [id=turbottest50436]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

aws_partition = "aws"
aws_region = "us-east-1"
resource_aka = "arn:aws:ssm:us-east-1:112233445566:document/turbottest50436"
resource_name = "turbottest50436"

Running SQL query: test-get-query.sql
[
  {
    "akas": [
      "arn:aws:ssm:us-east-1:112233445566:document/turbottest50436"
    ],
    "name": "turbottest50436",
    "tags": {
      "name": "turbottest50436"
    },
    "title": "turbottest50436"
  }
]
✔ PASSED

Running SQL query: test-hydrate-query.sql
[
  {
    "akas": [
      "arn:aws:ssm:us-east-1:112233445566:document/turbottest50436"
    ],
    "tags_src": [
      {
        "Key": "name",
        "Value": "turbottest50436"
      }
    ],
    "title": "turbottest50436"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "document_format": "YAML",
    "document_type": "Command",
    "document_version": "1",
    "name": "turbottest50436",
    "partition": "aws",
    "region": "us-east-1",
    "tags": {
      "name": "turbottest50436"
    },
    "title": "turbottest50436"
  }
]
✔ PASSED

Running SQL query: test-notfound-query.sql
null
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "akas": [
      "arn:aws:ssm:us-east-1:112233445566:document/turbottest50436"
    ],
    "name": "turbottest50436",
    "region": "us-east-1",
    "tags": {
      "name": "turbottest50436"
    },
    "title": "turbottest50436"
  }
]
✔ PASSED

POSTTEST: tests/aws_ssm_document

TEARDOWN: tests/aws_ssm_document

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>

```
> select name, arn from aws_ssm_document where arn = 'arn:aws:ssm:ap-south-1:112233445566:document/AWS-ASGEnterStandby'
+---------------------+------------------------------------------------------------------+
| name                | arn                                                              |
+---------------------+------------------------------------------------------------------+
| AWS-ASGEnterStandby | arn:aws:ssm:ap-south-1:112233445566:document/AWS-ASGEnterStandby |
+---------------------+------------------------------------------------------------------+

> select name, arn from aws_ssm_document where arn = ''
+------+-----+
| name | arn |
+------+-----+
+------+-----+

Time: 3.8s.

> select name, arn from aws_ssm_document where arn = 'fdsdss:fdgs'
+------+-----+
| name | arn |
+------+-----+
+------+-----+

Time: 64ms.

```
</details>

### CODE REVIEW

File: aws/table_aws_ssm_document.go [hunk 1]
```diff
@@ -387,6 +416,18 @@ func getAwsSSMDocumentAkas(ctx context.Context, d *plugin.QueryData, h *plugin.H
 	return []string{aka}, nil
 }
 
+func getgetAwsSSMDocumentArn(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
+	akas, err := getAwsSSMDocumentAkas(ctx, d, h)
```
Comment (cbruno10) [inline aws/table_aws_ssm_document.go:420]: In this function, can we instead compose the ARN from the information we have available? This helps protect us against future changes in `akas` where the first entry isn't always the ARN

File: aws/table_aws_ssm_document.go [hunk 2]
```diff
@@ -387,6 +416,18 @@ func getAwsSSMDocumentAkas(ctx context.Context, d *plugin.QueryData, h *plugin.H
 	return []string{aka}, nil
 }
 
+func getgetAwsSSMDocumentArn(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```
Comment (cbruno10) [inline aws/table_aws_ssm_document.go:419]:
```suggestion
func getAwsSSMDocumentArn(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```

File: aws/table_aws_ssm_document.go [hunk 3]
```diff
@@ -293,13 +301,34 @@ func listAwsSSMDocuments(ctx context.Context, d *plugin.QueryData, _ *plugin.Hyd
...
+	metrixRegion := d.EqualsQualString(matrixKeyRegion)
+	arnSplit := strings.Split(arn, ":") // Split ARN to get the region
+
+	// Invalid arn check
+	if len(arnSplit) < 3 {
+		return nil, nil
+	}
+
+	// The same document name can be used in different regions.
+	// If a name is specified in the WHERE clause, the "get config" function will be executed. However, if the specified document name is available in different regions, the query will throw an error stating that the "get" call returned 23 results and the key column is not globally unique.
```
Comment (cbruno10) [inline aws/table_aws_ssm_document.go:324]: I don't think this line is true anymore, since we don't have the `name` column as a key column for the GetConfig anymore

File: aws/table_aws_ssm_document.go [hunk 4]
```diff
@@ -293,13 +301,34 @@ func listAwsSSMDocuments(ctx context.Context, d *plugin.QueryData, _ *plugin.Hyd
...
+	// Check for region specified in .spc file and the region specified in ARN
```
Comment (cbruno10) [inline aws/table_aws_ssm_document.go:325]:
```suggestion
	// Skip ARNs in other regions
```

File: aws/table_aws_ssm_document.go [hunk 5]
```diff
@@ -293,13 +301,34 @@ func listAwsSSMDocuments(ctx context.Context, d *plugin.QueryData, _ *plugin.Hyd
...
+		}
+		arn = data.(string)
 	} else {
-		name = d.EqualsQuals["name"].GetStringValue()
+		arn = d.EqualsQuals["arn"].GetStringValue()
+	}
+	metrixRegion := d.EqualsQualString(matrixKeyRegion)
+	arnSplit := strings.Split(arn, ":") // Split ARN to get the region
+
+	// Invalid arn check
```
Comment (cbruno10) [inline aws/table_aws_ssm_document.go:318]:
```suggestion
	// Invalid ARN check
```

**Review by cbruno10 — CHANGES_REQUESTED** [review]
@ParthaI Please see suggestions. Can you please also update or add an example showing how to get an SSM document by region? Thanks!

**Review by cbruno10 — APPROVED** [review]
