### PR TITLE
Fix `aws_wafv2_web_acl` not returning `CLOUDFRONT` resources closes #1747

### LINKED ISSUE #1747: Can't list CloudFront related AWS Web Acls using aws_wafv2_web_acl
**Describe the bug**
I have CloudFront and Regional level AWS WAF V2 WebAcls.

aws_wafv2_web_acl query isn't listing CloudFront related Web Acls. Only Regional Web Acls are listing. 

**Steampipe version (`steampipe -v`)**
Steampipe v0.19.4

**Plugin version (`steampipe plugin list`)**
+--------------------------------------------+---------+-------------+
| Installed Plugin                           | Version | Connections |
+--------------------------------------------+---------+-------------+
| hub.steampipe.io/plugins/turbot/aws@latest | 0.101.0 | aws_dev     |
| hub.steampipe.io/plugins/turbot/rss@latest  | 0.4.0     | rss               |
+--------------------------------------------+---------+-------------+

**To reproduce**

1. First install steappipe cli and steampipe aws plugin.
2. Configure aws.spc file and This is my steampipe aws config:

```
connection "aws_dev" {
 plugin = "aws"
 regions = ["*"] # Specific regions
 profile = "development"
}
```

3. I wanted to list all aws Web Acls ( Cloudfront and Regional ). I wrote below query,

```
select
  name,
  scope
from
  aws_wafv2_web_acl;
```

output:
+--------+----------+
| name   | scope    |
+--------+----------+
| XXXXXX | REGIONAL |
+--------+----------+

So I saw that this steampipe table isn't listing Cloudfront related WebAcls but only listing Regional data.

Then I wrote shell script using AWS CLI query to retrieve data and find the code below,

```
for region in $(aws ec2 describe-regions --profile development --output text | cut -f4); do
    echo "Region: ${region}"
    aws wafv2 list-web-acls --profile development --scope="CLOUDFRONT" --region="${region}"
    echo ""
done
```
And using this AWS CLI script, it is returning Cloudfront related web acls, but not from steampipe query.

**Expected behavior**
Steampipe query (aws_wafv2_web_acl) should return both CloudFront and Regional AWS WAF V2 Web Acls

### PR DESCRIPTION
**Pull request by karanpopat**
# Integration test logs
<details>
  <summary>Logs</summary>

```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>

```
> select
  name,
  id,
  scope,
  description,
  capacity,
  managed_by_firewall_manager
from
  aws_wafv2_web_acl;
+---------------------+--------------------------------------+------------+-------------------+----------+-----------------------------+
| name                | id                                   | scope      | description       | capacity | managed_by_firewall_manager |
+---------------------+--------------------------------------+------------+-------------------+----------+-----------------------------+
| test-waf-acl-global | 73c9276d-be09-4a0d-9b67-83c87862e9e5 | CLOUDFRONT | test-waf-acl      | 0        | false                       |
| test-waf-acl-use1   | f473a3fe-360a-4087-9cee-e1a9ecd1dfad | REGIONAL   | test-waf-acl-use1 | 0        | false                       |
+---------------------+--------------------------------------+------------+-------------------+----------+-----------------------------+
```
</details>

### CODE REVIEW

File: aws/service.go [hunk 1]
```diff
@@ -1445,6 +1445,10 @@ func getClientForQuerySupportedRegionWithExclusions(ctx context.Context, d *plug
 		return nil, fmt.Errorf("getClientForQuerySupportedRegion called without a region in QueryData")
 	}
 
+	if region == "global" {
```
Comment (ParthaI) [inline aws/service.go:1448]: @karanpopat please add a comment regarding why we need this check for future understanding.

**Review by ParthaI — COMMENTED** [review]
@karanpopat please take a look at the review comments, Thanks!

**Review by ParthaI — APPROVED** [review]
LGTM

**Review by misraved — APPROVED** [review]
