### PR TITLE
Handling exceptions aws_macie2_classification_job table. Closes #641

### LINKED ISSUE #641: Handling exceptions aws_macie2_classification_job table
**Describe the bug**
`aws_macie2_classification_job` table returns AccessDeniedException in case any one of the regions is configured in `aws.spc `file is not enabled with Macie.

Also, provide the Macie service enabled/disabled status part of this table.

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**

**Error when IAM user with all required permissions and only 1 region is enabled with Macie**
```
> select * from aws_aab.aws_macie2_classification_job
Error: AccessDeniedException: Macie is not enabled.
> select * from aws_aab.aws_macie2_classification_job where region = 'us-east-1'
+--------------+----------------------------------+-------------------------------------------------------------------------------------------+------------+----------+--------------------------------------+------
| name         | job_id                           | arn                                                                                       | job_status | job_type | client_token                         | creat
+--------------+----------------------------------+-------------------------------------------------------------------------------------------+------------+----------+--------------------------------------+------
| bucket-audit | f9d91733ace0a9sdfdsfsdfsdfsd98916e | arn:aws:macie2:us-east-1:123493682495:classification-job/f9d91733ace0a93c09e8da13f598916e | COMPLETE   | ONE_TIME | cf6b6918-9c3f-4a33-887b-f4f834a1046d | 2021-
+--------------+----------------------------------+-------------------------------------------------------------------------------------------+------------+----------+--------------------------------------+------
```
**The exception remains the same with a different message when a user with no IAM privileges, tries to query** 

```

> select * from aws_macie2_classification_job
Error: AccessDeniedException: User: arn:aws:iam::533793682495:user/macie-test is not authorized to perform: macie2:ListClassificationJobs on resource: arn:aws:macie2:ap-south-1:533793682495:*
> .exit
```
**CLI Output**

```
turbot-macpro-raj:steampipe-mod-aws-top10 raj$ aws macie2 list-classification-jobs --profile devaab --region us-east-1
{
    "items": [
        {
            "bucketDefinitions": [
                {
                    "accountId": "123453682495",
                    "buckets": [
                        "andrew-turbot-test-bucket",
                        "aws-logs-123453682495-us-east-1"
                    ]
                }
            ],
            "createdAt": "2021-09-06T18:13:46.335482+00:00",
            "jobId": "f9d91733ace0a93c09e8da13f598916e",
            "jobStatus": "COMPLETE",
            "jobType": "ONE_TIME",
            "lastRunErrorStatus": {
                "code": "NONE"
            },
            "name": "bucket-audit"
        }
    ]
}
turbot-macpro-raj:steampipe-mod-aws-top10 raj$ aws macie2 list-classification-jobs --profile devaab --region ap-south-1

An error occurred (AccessDeniedException) when calling the ListClassificationJobs operation: Macie is not enabled.

turbot-macpro-raj:steampipe-mod-aws-top10 raj$ aws macie2 list-classification-jobs --profile devaab-onlyrds --region ap-south-1

An error occurred (AccessDeniedException) when calling the ListClassificationJobs operation: User: arn:aws:iam::123453682495:user/macie-test is not authorized to perform: macie2:ListClassificationJobs on resource: arn:aws:macie2:ap-south-1:123453682495:*
turbot-macpro-raj:steampipe-mod-aws-top10 raj$ 
```

**Expected behavior**
Do we need to handle the message, not the exception?

**Additional context**

### PR DESCRIPTION
**Pull request by bigdatasourav**
# Example query results
<details>
  <summary>Results</summary>
  
```
> select * from aws_macie2_classification_job where job_id = 'f9d91733ace0a93c09e8da13f598916e'
+--------------+----------------------------------+-------------------------------------------------------------------------------------------+------------+----------+-------------------------------------
| name         | job_id                           | arn                                                                                       | job_status | job_type | client_token                        
+--------------+----------------------------------+-------------------------------------------------------------------------------------------+------------+----------+-------------------------------------
| bucket-audit | f9d91733ace0a93c09e8da13f598916e | arn:aws:macie2:us-east-1:533793682495:classification-job/f9d91733ace0a93c09e8da13f598916e | COMPLETE   | ONE_TIME | cf6b6918-9c3f-4a33-887b-f4f834a1046d
+--------------+----------------------------------+-------------------------------------------------------------------------------------------+------------+----------+-------------------------------------


> select * from aws_macie2_classification_job
+--------------+----------------------------------+-------------------------------------------------------------------------------------------+------------+----------+-------------------------------------
| name         | job_id                           | arn                                                                                       | job_status | job_type | client_token                        
+--------------+----------------------------------+-------------------------------------------------------------------------------------------+------------+----------+-------------------------------------
| bucket-audit | f9d91733ace0a93c09e8da13f598916e | arn:aws:macie2:us-east-1:533793682495:classification-job/f9d91733ace0a93c09e8da13f598916e | COMPLETE   | ONE_TIME | cf6b6918-9c3f-4a33-887b-f4f834a1046d
+--------------+----------------------------------+-------------------------------------------------------------------------------------------+------------+----------+-------------------------------------

```

# User who do not have permission for macie -
> select * from aws_macie2_classification_job
Error: AccessDeniedException: User: arn:aws:iam::533793682495:user/test_macie is not authorized to perform: macie2:ListClassificationJobs on resource: arn:aws:macie2:ap-south-1:533793682495:*
</details>

### CODE REVIEW

File: aws/table_aws_macie2_classification_job.go [hunk 1]
```diff
@@ -161,6 +162,15 @@ func listMacie2ClassificationJobs(ctx context.Context, d *plugin.QueryData, _ *p
 			return !isLast
 		},
 	)
+	if err != nil {
+		if awsErr, ok := err.(awserr.Error); ok {
+			// Throws AccessDeniedException: Macie is not enabled. when AWS Macie is not enabled in a region
+			if awsErr.Message() == "Macie is not enabled." {
```
Comment (rajlearner17) [inline aws/table_aws_macie2_classification_job.go:168]: Should we mention why we are validating the `awsErr.Message()`? This will help developers to understand or at least to know that, AWS API response has the same exception code for 2 different cases.

File: aws/table_aws_macie2_classification_job.go [hunk 2]
```diff
@@ -177,6 +187,11 @@ func getMacie2ClassificationJob(ctx context.Context, d *plugin.QueryData, h *plu
 		id = d.KeyColumnQuals["job_id"].GetStringValue()
 	}
 
+	// empty check for job id
+	if id == "" {
```
Comment (cbruno10) [inline aws/table_aws_macie2_classification_job.go:191]: when would ID be empty?

File: aws/table_aws_macie2_classification_job.go [hunk 3]
```diff
@@ -191,6 +206,13 @@ func getMacie2ClassificationJob(ctx context.Context, d *plugin.QueryData, h *plu
 	// Get call
 	op, err := svc.DescribeClassificationJob(params)
 	if err != nil {
+		if awsErr, ok := err.(awserr.Error); ok {
+			// Throws AccessDeniedException: Macie is not enabled. when AWS Macie is not enabled in a region
+			if awsErr.Message() == "Macie is not enabled." {
```
Comment (cbruno10) [inline aws/table_aws_macie2_classification_job.go:211]: @bigdatasourav Do you have a full output of what the error object looks like for reference?

File: aws/table_aws_macie2_classification_job.go (hunk 2 above)
Comment (bigdatasourav) [reply aws/table_aws_macie2_classification_job.go:193]: @cbruno10 user can provide empty value in get call - `select * from aws_macie2_classification_job where job_id = ''`. API should not be called with an empty value.

File: aws/table_aws_macie2_classification_job.go (hunk 3 above)
Comment (bigdatasourav) [reply aws/table_aws_macie2_classification_job.go:213]: @cbruno10 It is available in the issue - https://github.com/turbot/steampipe-plugin-aws/issues/641

**Review by cbruno10 — APPROVED** [review]

**Review by rajlearner17 — APPROVED** [review]
LGTM
