### PR TITLE
Getting an error as Error: NotFound: Topic does not exist, status code: 404 from aws_sns_topic_subscription table. Closes #335

### LINKED ISSUE #335: Getting an error as `Error: NotFound: Topic does not exist, status code: 404` from aws_sns_topic_subscription table
**Describe the bug**
Execute the below query and got the above error.

```
select * from aws_sns_topic_subscription
Error: NotFound: Topic does not exist
	status code: 404, request id: 6a97ba47-7e3e-5ff1-b12b-e2bc1434b884
```

**Steampipe version (`steampipe -v`)**
 v0.4.0

**Plugin version (`steampipe plugin list`)**
aws: v0.13.0

**To reproduce**
Just execute the above query. Not sure if there any subscription in the account for which Topic doesn't exist. If that might be the case. 

**Additional context**

### PR DESCRIPTION
**Pull request by visiit**
# Integration test logs
<details>
  <summary>Logs</summary>
  
```
vishalkumar@Vishals-MacBook-Air aws-test % TURBOT_PROFILE=shaktiman TF_VAR_aws_profile=shaktiman ./tint.js tests/aws_sns_topic_subscription
No env file present for the current environment:  staging
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT undefined

SETUP: tests/aws_sns_topic_subscription []

PRETEST: tests/aws_sns_topic_subscription

TEST: tests/aws_sns_topic_subscription
Running terraform
data.aws_region.alternate: Refreshing state...
data.aws_caller_identity.current: Refreshing state...
data.aws_region.primary: Refreshing state...
data.aws_partition.current: Refreshing state...
data.null_data_source.resource: Refreshing state...
aws_sqs_queue.aws_sns_subscription: Creating...
aws_sns_topic.aws_sns_subscription: Creating...
aws_sns_topic.aws_sns_subscription: Creation complete after 4s [id=arn:aws:sns:us-east-1:123456789012:turbottest53265]
aws_sqs_queue.aws_sns_subscription: Creation complete after 4s [id=https://sqs.us-east-1.amazonaws.com/123456789012/turbottest53265]
aws_sns_topic_subscription.named_test_resource: Creating...
aws_sns_topic_subscription.named_test_resource: Creation complete after 5s [id=arn:aws:sns:us-east-1:123456789012:turbottest53265:8c3017e6-f431-4c43-ad29-6ac454b68f68]

Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals


Apply complete! Resources: 3 added, 0 changed, 0 destroyed.

Outputs:

account_id = 123456789012
aws_partition = aws
aws_region = us-east-1
endpoint = arn:aws:sqs:us-east-1:123456789012:turbottest53265
resource_aka = arn:aws:sns:us-east-1:123456789012:turbottest53265:8c3017e6-f431-4c43-ad29-6ac454b68f68
resource_name = turbottest53265
topic_arn = arn:aws:sns:us-east-1:123456789012:turbottest53265

Running SQL query: test-get-query.sql
[
  {
    "endpoint": "arn:aws:sqs:us-east-1:123456789012:turbottest53265",
    "protocol": "sqs",
    "topic_arn": "arn:aws:sns:us-east-1:123456789012:turbottest53265"
  }
]
✔ PASSED

Running SQL query: test-get-subscription-attributes-query.sql
[
  {
    "confirmation_was_authenticated": true,
    "delivery_policy": null,
    "effective_delivery_policy": null,
    "filter_policy": null,
    "pending_confirmation": false,
    "raw_message_delivery": false,
    "redrive_policy": null
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "endpoint": "arn:aws:sqs:us-east-1:123456789012:turbottest53265",
    "owner": "123456789012",
    "protocol": "sqs",
    "subscription_arn": "arn:aws:sns:us-east-1:123456789012:turbottest53265:8c3017e6-f431-4c43-ad29-6ac454b68f68",
    "topic_arn": "arn:aws:sns:us-east-1:123456789012:turbottest53265"
  }
]
✔ PASSED

Running SQL query: test-notfound-query.sql
null
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "account_id": "123456789012",
    "akas": [
      "arn:aws:sns:us-east-1:123456789012:turbottest53265:8c3017e6-f431-4c43-ad29-6ac454b68f68"
    ],
    "partition": "aws",
    "region": "us-east-1",
    "title": "8c3017e6-f431-4c43-ad29-6ac454b68f68"
  }
]
✔ PASSED

POSTTEST: tests/aws_sns_topic_subscription

TEARDOWN: tests/aws_sns_topic_subscription

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
Add example SQL query results here (please include the input queries as well)
```
</details>

### CODE REVIEW

**Comment by Subhajit97** [comment]
@visiit Can you please verify the `subscription_arn` column also?
If there are any subscription waiting for confirmation, AWS returns the value as `PendingConfirmation`, when perform list call.
```
> select subscription_arn, akas from aws_pikachu.aws_sns_topic_subscription where topic_arn like '%test-topic'
+---------------------+-------------------------+
| subscription_arn    | akas                    |
+---------------------+-------------------------+
| PendingConfirmation | ["PendingConfirmation"] |
+---------------------+-------------------------
```
Here is the response getting using AWS CLI
```
{
    "SubscriptionArn": "PendingConfirmation",
    "Owner": "1234567898012",
    "Protocol": "https",
    "Endpoint": "https://www.test.com",
    "TopicArn": "arn:aws:sns:us-east-2:1234567898012:test-topic"
}
```
Though the get function returns proper value

**Review by Subhajit97 — CHANGES_REQUESTED** [review]
@visiit I have left a comment. Can you please verify once? Thanks!

**Comment by visiit** [comment]
@Subhajit97 When the status is not confirmed, subscription_id is not generated that's why in that time SubscriptionArn is coming as `PendingConfirmation`.image

**Comment by cbruno10** [comment]
@johnsmyth Since subscriptions pending confirmation do not have an ID and no ARN (so we also can't call the get/hydrate functions), should we skip showing these in the table results, or is it valuable to show the pending confirmation ones but put in a placeholder for the ID/ARN?

**Comment by cbruno10** [comment]
To better handle subscriptions pending confirmation, I suggest that if `Attributes.PendingConfirmation` is `true`, then:
- Set `akas` as `[]` or `null` (@LalitTurbot - What is our default for rows with no AKAs?)
- Set `SubscriptionArn` to `null` (not sure if our transformation functions can handle that though, may need a separate function)

File: aws/table_aws_sns_topic_subscription.go [hunk 1]
```diff
@@ -31,7 +32,7 @@ func tableAwsSnsTopicSubscription(_ context.Context) *plugin.Table {
 				Name:        "subscription_arn",
 				Description: "Amazon Resource Name of the subscription.",
 				Type:        proto.ColumnType_STRING,
-				Transform:   transform.FromField("Attributes.SubscriptionArn"),
+				Transform:   transform.FromField("Attributes.SubscriptionArn").Transform(subscriptionArnNotconformStatus),
```
Comment (Subhajit97) [inline aws/table_aws_sns_topic_subscription.go:35]:
```suggestion
				Transform:   transform.FromField("Attributes.SubscriptionArn").Transform(subscriptionArnNotconfirmStatus),
```

File: aws/table_aws_sns_topic_subscription.go [hunk 2]
```diff
@@ -193,7 +194,36 @@ func getSubscriptionAttributes(ctx context.Context, d *plugin.QueryData, h *plug
...
 }
+
+//// TRANSFORM FUNCTIONS
+
+func subscriptionArnNotconformStatus(ctx context.Context, d *transform.TransformData) (interface{}, error) {
+	plugin.Logger(ctx).Trace("pendingConfirmationArn")
+	arn := types.SafeString(d.Value)
+
+	if arn == "PendingConfirmation" {
+		return "null", nil
```
Comment (Subhajit97) [inline aws/table_aws_sns_topic_subscription.go:215]:
```suggestion
		return nil, nil
```

File: aws/table_aws_sns_topic_subscription.go (hunk 1 above)
Comment (Subhajit97) [reply aws/table_aws_sns_topic_subscription.go:35]: @visiit Can we use `NullIfEqual()` transform for this?

**Review by Subhajit97 — APPROVED** [review]
LGTM

**Review by cbruno10 — APPROVED** [review]
