### PR TITLE
Get call not working for table aws_codepipeline_pipeline closes #531

### LINKED ISSUE #531: Get call not working for table aws_codepipeline_pipeline
**Describe the bug**
```
> select * from aws_codepipeline_pipeline where name = 'test-final'
+------+-----+------------+----------+------------+---------+----------------+-----------------+--------+----------+-------+------+------+-----------+--------+------------+
| name | arn | created_at | role_arn | updated_at | version | encryption_key | artifact_stores | stages | tags_src | title | tags | akas | partition | region | account_id |
+------+-----+------------+----------+------------+---------+----------------+-----------------+--------+----------+-------+------+------+-----------+--------+------------+
+------+-----+------------+----------+------------+---------+----------------+-----------------+--------+----------+-------+------+------+-----------+--------+------------+
> select * from aws_codepipeline_pipeline
+-----------------+-------------------------------------------------------------+---------------------+---------------------------------------------------------------------------------------------+-------
| name            | arn                                                         | created_at          | role_arn                                                                                    | update
+-----------------+-------------------------------------------------------------+---------------------+---------------------------------------------------------------------------------------------+-------
| turbottest60077 | arn:aws:codepipeline:us-east-1:013122550996:turbottest60077 | 2021-07-07 08:05:54 | arn:aws:iam::013122550996:role/turbottest60077                                              | 2021-0
|                 |                                                             |                     |                                                                                             |       
| test-final      | arn:aws:codepipeline:us-east-1:013122550996:test-final      | 2019-12-03 11:53:10 | arn:aws:iam::013122550996:role/service-role/AWSCodePipelineServiceRole-us-east-1-test-final | 2019-1
|                 |                                                             |                     |                                                                                             |       
+-----------------+-------------------------------------------------------------+---------------------+---------------------------------------------------------------------------------------------+-------

```
**Steampipe version (`steampipe -v`)**
Example: v0.5.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by ParthaI**
# Integration test logs
<details>
  <summary>Logs</summary>
  
```
No env file present for the current environment:  staging 
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT 300

SETUP: tests/aws_codepipeline_pipeline []

PRETEST: tests/aws_codepipeline_pipeline

TEST: tests/aws_codepipeline_pipeline
Running terraform
data.aws_region.alternate: Refreshing state...
data.aws_region.primary: Refreshing state...
data.aws_partition.current: Refreshing state...
data.aws_caller_identity.current: Refreshing state...
data.null_data_source.resource: Refreshing state...
aws_kms_key.named_test_resource: Creating...
aws_s3_bucket.codepipeline_bucket: Creating...
aws_codestarconnections_connection.example: Creating...
aws_iam_role.codepipeline_role: Creating...
aws_codestarconnections_connection.example: Creation complete after 3s [id=arn:aws:codestar-connections:us-east-1:123456789012:connection/3925a91c-4232-4a44-bb72-a116ae5eeccd]
aws_iam_role.codepipeline_role: Creation complete after 4s [id=turbottest76497]
aws_kms_key.named_test_resource: Creation complete after 5s [id=2b7a6a8b-1698-460e-b88d-31430419a2c0]
aws_kms_alias.s3kmskey: Creating...
aws_kms_alias.s3kmskey: Creation complete after 2s [id=alias/my-key-alias_turbottest76497]
aws_s3_bucket.codepipeline_bucket: Still creating... [10s elapsed]
aws_s3_bucket.codepipeline_bucket: Creation complete after 16s [id=turbottest76497]
aws_iam_role_policy.codepipeline_policy: Creating...
aws_codepipeline.named_test_resource: Creating...
aws_iam_role_policy.codepipeline_policy: Creation complete after 2s [id=turbottest76497:turbottest76497]
aws_codepipeline.named_test_resource: Creation complete after 3s [id=turbottest76497]

Warning: Deprecated Resource

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals


Apply complete! Resources: 7 added, 0 changed, 0 destroyed.

Outputs:

account_id = 123456789012
aws_partition = aws
encryption_key = arn:aws:kms:us-east-1:123456789012:alias/my-key-alias_turbottest76497
region_name = us-east-1
resource_aka = arn:aws:codepipeline:us-east-1:123456789012:turbottest76497
resource_name = turbottest76497
role_arn = arn:aws:iam::123456789012:role/turbottest76497

Running SQL query: test-get-query.sql
[
  {
    "arn": "arn:aws:codepipeline:us-east-1:123456789012:turbottest76497",
    "encryption_key": {
      "Id": "arn:aws:kms:us-east-1:123456789012:alias/my-key-alias_turbottest76497",
      "Type": "KMS"
    },
    "name": "turbottest76497",
    "role_arn": "arn:aws:iam::123456789012:role/turbottest76497",
    "tags_src": [],
    "title": "turbottest76497"
  }
]
✔ PASSED

Running SQL query: test-hydrate-query.sql
[
  {
    "akas": [
      "arn:aws:codepipeline:us-east-1:123456789012:turbottest76497"
    ],
    "name": "turbottest76497",
    "tags": {},
    "title": "turbottest76497"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql
[
  {
    "arn": "arn:aws:codepipeline:us-east-1:123456789012:turbottest76497",
    "name": "turbottest76497",
    "tags": {},
    "title": "turbottest76497"
  }
]
✔ PASSED

Running SQL query: test-not-found-query.sql
null
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "account_id": "123456789012",
    "akas": [
      "arn:aws:codepipeline:us-east-1:123456789012:turbottest76497"
    ],
    "name": "turbottest76497",
    "region": "us-east-1",
    "title": "turbottest76497"
  }
]
✔ PASSED

POSTTEST: tests/aws_codepipeline_pipeline

TEARDOWN: tests/aws_codepipeline_pipeline

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
> select * from aws_codepipeline_pipeline where name='test-pipeline'
+---------------+-----------------------------------------------------------+------------+----------------------------------------------------------------------------------------------------------+-------
| name          | arn                                                       | created_at | role_arn                                                                                                 | update
+---------------+-----------------------------------------------------------+------------+----------------------------------------------------------------------------------------------------------+-------
| test-pipeline | arn:aws:codepipeline:us-east-2:986325076436:test-pipeline | <null>     | arn:aws:iam::986325076436:role/service-role/AWSCodePipelineServiceRole-us-east-1-test-steampipe-pipeline | <null>
+---------------+-----------------------------------------------------------+------------+----------------------------------------------------------------------------------------------------------+-------

```
</details>

### CODE REVIEW

File: aws/table_aws_codepipeline_pipeline.go [hunk 1]
```diff
@@ -30,13 +30,15 @@ func tableAwsCodepipelinePipeline(_ context.Context) *plugin.Table {
 				Name:        "name",
 				Description: "The name of the pipeline.",
 				Type:        proto.ColumnType_STRING,
+				Hydrate:     getCodepipelinePipeline,
```
Comment (Subhajit97) [inline aws/table_aws_codepipeline_pipeline.go:33]: Is this required, since we are getting `name` from both GET and LIST?

File: aws/table_aws_codepipeline_pipeline.go [hunk 2]
```diff
@@ -30,13 +30,15 @@ func tableAwsCodepipelinePipeline(_ context.Context) *plugin.Table {
...
+				Transform:   transform.FromField("Name", "Pipeline.Name"),
 			},
 			{
 				Name:        "arn",
 				Description: "The Amazon Resource Name (ARN) of the pipeline.",
 				Hydrate:     getCodepipelinePipeline,
 				Type:        proto.ColumnType_STRING,
-				Transform:   transform.FromField("Metadata.PipelineArn"),
+				Transform:   transform.FromField("PipelineArn", "Metadata.PipelineArn"),
```
Comment (Subhajit97) [inline aws/table_aws_codepipeline_pipeline.go:41]: Why we need 2 different path, since we have added `Hydrate` in it?
```suggestion
				Transform:   transform.FromField("Metadata.PipelineArn"),
```

File: aws/table_aws_codepipeline_pipeline.go [hunk 3]
```diff
@@ -49,7 +51,7 @@ func tableAwsCodepipelinePipeline(_ context.Context) *plugin.Table {
 				Description: "The Amazon Resource Name (ARN) for AWS CodePipeline to use to either perform actions with no actionRoleArn, or to use to assume roles for actions with an actionRoleArn.",
 				Hydrate:     getCodepipelinePipeline,
 				Type:        proto.ColumnType_STRING,
-				Transform:   transform.FromField("Pipeline.RoleArn"),
+				Transform:   transform.FromField("RoleArn", "Pipeline.RoleArn"),
```
Comment (Subhajit97) [inline aws/table_aws_codepipeline_pipeline.go:54]:
```suggestion
				Transform:   transform.FromField("Pipeline.RoleArn"),
```

File: aws/table_aws_codepipeline_pipeline.go [hunk 4]
```diff
@@ -67,21 +69,21 @@ func tableAwsCodepipelinePipeline(_ context.Context) *plugin.Table {
 				Description: "The encryption key used to encrypt the data in the artifact store, such as an AWS Key Management Service (AWS KMS) key. If this is undefined, the default key for Amazon S3 is used.",
 				Hydrate:     getCodepipelinePipeline,
 				Type:        proto.ColumnType_JSON,
-				Transform:   transform.FromField("Pipeline.ArtifactStore.EncryptionKey"),
+				Transform:   transform.FromField("EncryptionKey", "Pipeline.ArtifactStore.EncryptionKey"),
```
Comment (Subhajit97) [inline aws/table_aws_codepipeline_pipeline.go:72]:
```suggestion
				Transform:   transform.FromField("Pipeline.ArtifactStore.EncryptionKey"),
```

File: aws/table_aws_codepipeline_pipeline.go [hunk 5]
```diff
@@ -67,21 +69,21 @@ func tableAwsCodepipelinePipeline(_ context.Context) *plugin.Table {
...
 			},
 			{
 				Name:        "artifact_stores",
 				Description: "A mapping of artifactStore objects and their corresponding AWS Regions. There must be an artifact store for the pipeline Region and for each cross-region action in the pipeline.",
 				Hydrate:     getCodepipelinePipeline,
 				Type:        proto.ColumnType_JSON,
-				Transform:   transform.FromField("Pipeline.ArtifactStores"),
+				Transform:   transform.FromField("ArtifactStores", "Pipeline.ArtifactStores"),
```
Comment (Subhajit97) [inline aws/table_aws_codepipeline_pipeline.go:79]:
```suggestion
				Transform:   transform.FromField("Pipeline.ArtifactStores"),
```

File: aws/table_aws_codepipeline_pipeline.go [hunk 6]
```diff
@@ -67,21 +69,21 @@ func tableAwsCodepipelinePipeline(_ context.Context) *plugin.Table {
...
 			},
 			{
 				Name:        "stages",
 				Description: "The stage in which to perform the action.",
 				Hydrate:     getCodepipelinePipeline,
 				Type:        proto.ColumnType_JSON,
-				Transform:   transform.FromField("Pipeline.Stages"),
+				Transform:   transform.FromField("Stages", "Pipeline.Stages"),
```
Comment (Subhajit97) [inline aws/table_aws_codepipeline_pipeline.go:86]:
```suggestion
				Transform:   transform.FromField("Pipeline.Stages"),
```

File: aws/table_aws_codepipeline_pipeline.go [hunk 7]
```diff
@@ -96,7 +98,8 @@ func tableAwsCodepipelinePipeline(_ context.Context) *plugin.Table {
 				Name:        "title",
 				Description: resourceInterfaceDescription("title"),
 				Type:        proto.ColumnType_STRING,
-				Transform:   transform.FromField("Name"),
+				Hydrate:     getCodepipelinePipeline,
```
Comment (Subhajit97) [inline aws/table_aws_codepipeline_pipeline.go:101]:
```suggestion
```

File: aws/table_aws_codepipeline_pipeline.go [hunk 8]
```diff
@@ -110,7 +113,7 @@ func tableAwsCodepipelinePipeline(_ context.Context) *plugin.Table {
 				Description: resourceInterfaceDescription("akas"),
 				Type:        proto.ColumnType_JSON,
 				Hydrate:     getCodepipelinePipeline,
-				Transform:   transform.FromField("Metadata.PipelineArn").Transform(transform.EnsureStringArray),
+				Transform:   transform.FromField("PipelineArn", "Metadata.PipelineArn").Transform(transform.EnsureStringArray),
```
Comment (Subhajit97) [inline aws/table_aws_codepipeline_pipeline.go:116]:
```suggestion
				Transform:   transform.FromField("Metadata.PipelineArn").Transform(transform.EnsureStringArray),
```

**Review by Subhajit97 — CHANGES_REQUESTED** [review]
@ParthaI Please see comments, thanks!

**Review by Subhajit97 — APPROVED** [review]

**Review by cbruno10 — APPROVED** [review]
