### PR TITLE
Handle unsupported region check for the table aws_ec2_managed_prefix_list closes #1576

### LINKED ISSUE #1576: Handle unsupported region check for the table aws_ec2_managed_prefix_list
**Describe the bug**

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by ParthaI**
# Integration test logs
<details>
  <summary>Logs</summary>

```
➜  aws-test git:(iisue-1576) ✗ ./tint.js aws_ec2_managed_prefix_list
No env file present for the current environment:  staging 
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT undefined

SETUP: tests/aws_ec2_managed_prefix_list []

PRETEST: tests/aws_ec2_managed_prefix_list

TEST: tests/aws_ec2_managed_prefix_list
Running terraform
data.aws_caller_identity.current: Reading...
data.aws_region.primary: Reading...
data.aws_partition.current: Reading...
data.aws_region.primary: Read complete after 0s [id=us-east-1]
data.aws_partition.current: Read complete after 0s [id=aws]
data.aws_region.alternate: Reading...
data.aws_region.alternate: Read complete after 0s [id=us-east-2]
data.aws_caller_identity.current: Read complete after 1s [id=243142342352]
data.null_data_source.resource: Reading...
data.null_data_source.resource: Read complete after 0s [id=static]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_ec2_managed_prefix_list.named_test_resource will be created
  + resource "aws_ec2_managed_prefix_list" "named_test_resource" {
      + address_family = "IPv4"
      + arn            = (known after apply)
      + id             = (known after apply)
      + max_entries    = 5
      + name           = "turbottest67027"
      + owner_id       = (known after apply)
      + tags           = {
          + "name" = "turbottest67027"
        }
      + tags_all       = {
          + "name" = "turbottest67027"
        }
      + version        = (known after apply)

      + entry {
          + cidr        = (known after apply)
          + description = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + address_family = "IPv4"
  + arn            = (known after apply)
  + id             = (known after apply)
  + owner_id       = (known after apply)
  + resource_name  = "turbottest67027"
aws_ec2_managed_prefix_list.named_test_resource: Creating...
aws_ec2_managed_prefix_list.named_test_resource: Creation complete after 3s [id=pl-0157e2b1d3cd1244a]

Warning: Deprecated

  with data.null_data_source.resource,
  on variables.tf line 43, in data "null_data_source" "resource":
  43: data "null_data_source" "resource" {

The null_data_source was historically used to construct intermediate values
to re-use elsewhere in configuration, the same can now be achieved using
locals

(and one more similar warning elsewhere)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

address_family = "IPv4"
arn = "arn:aws:ec2:us-east-1:243142342352:prefix-list/pl-0157e2b1d3cd1244a"
id = "pl-0157e2b1d3cd1244a"
owner_id = "243142342352"
resource_name = "turbottest67027"

Running SQL query: test-list-query.sql
[
  {
    "address_family": "IPv4",
    "arn": "arn:aws:ec2:us-east-1:243142342352:prefix-list/pl-0157e2b1d3cd1244a",
    "id": "pl-0157e2b1d3cd1244a",
    "name": "turbottest67027",
    "owner_id": "243142342352"
  }
]
✔ PASSED

Running SQL query: test-notfound-query.sql
null
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "akas": [
      "arn:aws:ec2:us-east-1:243142342352:prefix-list/pl-0157e2b1d3cd1244a"
    ],
    "tags": {
      "name": "turbottest67027"
    },
    "title": "turbottest67027"
  }
]
✔ PASSED

POSTTEST: tests/aws_ec2_managed_prefix_list

TEARDOWN: tests/aws_ec2_managed_prefix_list

SUMMARY:

1/1 passed.


```
</details>

# Example query results
<details>
  <summary>Results</summary>

```
> select * from aws_ec2_managed_prefix_list
+-----------------------------------------------+----------------------+-----------------------------------------------------------------+-----------------+----------------+-------------+----------+---------------+---------+----------+-----------------------------------
| name                                          | id                   | arn                                                             | state           | address_family | max_entries | owner_id | state_message | version | tags_src | title                             
+-----------------------------------------------+----------------------+-----------------------------------------------------------------+-----------------+----------------+-------------+----------+---------------+---------+----------+-----------------------------------
| com.amazonaws.eu-west-2.s3                    | pl-7ca54015          | arn:aws:ec2:eu-west-2:aws:prefix-list/pl-7ca54015               | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.eu-west-2.s3        
| com.amazonaws.global.cloudfront.origin-facing | pl-93a247fa          | arn:aws:ec2:eu-west-2:aws:prefix-list/pl-93a247fa               | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.global.cloudfront.or
| com.amazonaws.global.groundstation            | pl-02781422c4c792145 | arn:aws:ec2:me-south-1:aws:prefix-list/pl-02781422c4c792145     | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.global.groundstation
| com.amazonaws.global.groundstation            | pl-0419ec9f6f614c525 | arn:aws:ec2:ap-south-1:aws:prefix-list/pl-0419ec9f6f614c525     | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.global.groundstation
| com.amazonaws.global.groundstation            | pl-033e44023025215c0 | arn:aws:ec2:eu-north-1:aws:prefix-list/pl-033e44023025215c0     | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.global.groundstation
| com.amazonaws.eu-north-1.dynamodb             | pl-adae4bc4          | arn:aws:ec2:eu-north-1:aws:prefix-list/pl-adae4bc4              | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.eu-north-1.dynamodb 
| com.amazonaws.me-south-1.dynamodb             | pl-c9b451a0          | arn:aws:ec2:me-south-1:aws:prefix-list/pl-c9b451a0              | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.me-south-1.dynamodb 
| com.amazonaws.global.groundstation            | pl-082b2916fa6d7b4b7 | arn:aws:ec2:eu-west-2:aws:prefix-list/pl-082b2916fa6d7b4b7      | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.global.groundstation
| com.amazonaws.global.cloudfront.origin-facing | pl-17b2577e          | arn:aws:ec2:me-south-1:aws:prefix-list/pl-17b2577e              | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.global.cloudfront.or
| com.amazonaws.eu-north-1.s3                   | pl-c3aa4faa          | arn:aws:ec2:eu-north-1:aws:prefix-list/pl-c3aa4faa              | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.eu-north-1.s3       
| com.amazonaws.us-east-1.dynamodb              | pl-02cd2c6b          | arn:aws:ec2:us-east-1:aws:prefix-list/pl-02cd2c6b               | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.us-east-1.dynamodb  
| com.amazonaws.ap-southeast-1.dynamodb         | pl-67a5400e          | arn:aws:ec2:ap-southeast-1:aws:prefix-list/pl-67a5400e          | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.ap-southeast-1.dynam
| com.amazonaws.ap-south-1.dynamodb             | pl-66a7420f          | arn:aws:ec2:ap-south-1:aws:prefix-list/pl-66a7420f              | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.ap-south-1.dynamodb 
| com.amazonaws.ap-northeast-1.dynamodb         | pl-78a54011          | arn:aws:ec2:ap-northeast-1:aws:prefix-list/pl-78a54011          | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.ap-northeast-1.dynam
| com.amazonaws.eu-west-2.dynamodb              | pl-b3a742da          | arn:aws:ec2:eu-west-2:aws:prefix-list/pl-b3a742da               | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.eu-west-2.dynamodb  
| com.amazonaws.global.cloudfront.origin-facing | pl-a3a144ca          | arn:aws:ec2:eu-central-1:aws:prefix-list/pl-a3a144ca            | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.global.cloudfront.or
| com.amazonaws.me-south-1.s3                   | pl-85a045ec          | arn:aws:ec2:me-south-1:aws:prefix-list/pl-85a045ec              | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.me-south-1.s3       
| com.amazonaws.ap-south-1.s3                   | pl-78a54011          | arn:aws:ec2:ap-south-1:aws:prefix-list/pl-78a54011              | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.ap-south-1.s3       
| com.amazonaws.global.groundstation            | pl-08a6a3685cc410c2d | arn:aws:ec2:ca-central-1:aws:prefix-list/pl-08a6a3685cc410c2d   | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.global.groundstation
| com.amazonaws.global.cloudfront.origin-facing | pl-82a045eb          | arn:aws:ec2:us-west-2:aws:prefix-list/pl-82a045eb               | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.global.cloudfront.or
| com.amazonaws.eu-central-1.dynamodb           | pl-66a5400f          | arn:aws:ec2:eu-central-1:aws:prefix-list/pl-66a5400f            | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.eu-central-1.dynamod
| com.amazonaws.global.cloudfront.origin-facing | pl-31a34658          | arn:aws:ec2:ap-southeast-1:aws:prefix-list/pl-31a34658          | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.global.cloudfront.or
| com.amazonaws.global.groundstation            | pl-0e5696d987d033653 | arn:aws:ec2:us-east-1:aws:prefix-list/pl-0e5696d987d033653      | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.global.groundstation
| com.amazonaws.ap-southeast-1.s3               | pl-6fa54006          | arn:aws:ec2:ap-southeast-1:aws:prefix-list/pl-6fa54006          | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.ap-southeast-1.s3   
| com.amazonaws.ca-central-1.s3                 | pl-7da54014          | arn:aws:ec2:ca-central-1:aws:prefix-list/pl-7da54014            | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.ca-central-1.s3     
| com.amazonaws.global.groundstation            | pl-0cc36273da754ebdc | arn:aws:ec2:us-west-2:aws:prefix-list/pl-0cc36273da754ebdc      | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.global.groundstation
| com.amazonaws.eu-central-1.s3                 | pl-6ea54007          | arn:aws:ec2:eu-central-1:aws:prefix-list/pl-6ea54007            | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.eu-central-1.s3     
| com.amazonaws.ap-southeast-3.dynamodb         | pl-67a5400e          | arn:aws:ec2:ap-southeast-3:aws:prefix-list/pl-67a5400e          | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.ap-southeast-3.dynam
| com.amazonaws.ap-northeast-1.s3               | pl-61a54008          | arn:aws:ec2:ap-northeast-1:aws:prefix-list/pl-61a54008          | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.ap-northeast-1.s3   
| com.amazonaws.global.cloudfront.origin-facing | pl-9aa247f3          | arn:aws:ec2:ap-south-1:aws:prefix-list/pl-9aa247f3              | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.global.cloudfront.or
| com.amazonaws.us-east-1.s3                    | pl-63a5400a          | arn:aws:ec2:us-east-1:aws:prefix-list/pl-63a5400a               | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.us-east-1.s3        
| com.amazonaws.global.groundstation            | pl-03743f81267c0a85e | arn:aws:ec2:eu-central-1:aws:prefix-list/pl-03743f81267c0a85e   | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.global.groundstation
| com.amazonaws.ca-central-1.dynamodb           | pl-4ea54027          | arn:aws:ec2:ca-central-1:aws:prefix-list/pl-4ea54027            | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.ca-central-1.dynamod
| com.amazonaws.us-west-2.vpc-lattice           | pl-0721453c7ac4ec009 | arn:aws:ec2:us-west-2:aws:prefix-list/pl-0721453c7ac4ec009      | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.us-west-2.vpc-lattic
| com.amazonaws.global.groundstation            | pl-0b03d185a97164807 | arn:aws:ec2:ap-northeast-1:aws:prefix-list/pl-0b03d185a97164807 | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.global.groundstation
| com.amazonaws.ap-southeast-3.s3               | pl-64a7420d          | arn:aws:ec2:ap-southeast-3:aws:prefix-list/pl-64a7420d          | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.ap-southeast-3.s3   
| com.amazonaws.global.cloudfront.origin-facing | pl-3b927c52          | arn:aws:ec2:us-east-1:aws:prefix-list/pl-3b927c52               | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.global.cloudfront.or
| com.amazonaws.global.cloudfront.origin-facing | pl-58a04531          | arn:aws:ec2:ap-northeast-1:aws:prefix-list/pl-58a04531          | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.global.cloudfront.or
| com.amazonaws.global.groundstation            | pl-087f83ba4f34e3bea | arn:aws:ec2:us-east-2:aws:prefix-list/pl-087f83ba4f34e3bea      | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.global.groundstation
| com.amazonaws.global.cloudfront.origin-facing | pl-38a64351          | arn:aws:ec2:ca-central-1:aws:prefix-list/pl-38a64351            | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.global.cloudfront.or
| com.amazonaws.global.cloudfront.origin-facing | pl-bca247d5          | arn:aws:ec2:ap-southeast-3:aws:prefix-list/pl-bca247d5          | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.global.cloudfront.or
| com.amazonaws.us-west-2.dynamodb              | pl-00a54069          | arn:aws:ec2:us-west-2:aws:prefix-list/pl-00a54069               | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.us-west-2.dynamodb  
| com.amazonaws.ap-northeast-2.s3               | pl-78a54011          | arn:aws:ec2:ap-northeast-2:aws:prefix-list/pl-78a54011          | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.ap-northeast-2.s3   
| com.amazonaws.us-west-2.s3                    | pl-68a54001          | arn:aws:ec2:us-west-2:aws:prefix-list/pl-68a54001               | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.us-west-2.s3        
| com.amazonaws.global.groundstation            | pl-0d9b804fe014a6a99 | arn:aws:ec2:ap-southeast-1:aws:prefix-list/pl-0d9b804fe014a6a99 | create-complete | IPv4           | <null>      | AWS      | <null>        | <null>  | []       | com.amazonaws.global.groundstation

```
</details>

### CODE REVIEW

File: aws/table_aws_ec2_managed_prefix_list.go [hunk 1]
```diff
@@ -22,7 +22,9 @@ func tableAwsEc2ManagedPrefixList(_ context.Context) *plugin.Table {
 		Description: "AWS EC2 Managed Prefix List",
 		List: &plugin.ListConfig{
 			IgnoreConfig: &plugin.IgnoreConfig{
-				ShouldIgnoreErrorFunc: shouldIgnoreErrors([]string{"InvalidAction", "InvalidRequest"}),
+				// We are dealing with the UnsupportedOperation error code as a result of the resource's unsupported area.
```
Comment (cbruno10) [inline aws/table_aws_ec2_managed_prefix_list.go:25]: @ParthaI This comment is a good start point, but doesn't explain why we need it specifically in this table.

Can you please update the comment so that it explains that we are ignoring the `UnsupportedOperation` error because while the EC2 service supports the `me-south-1` region (at least that's what I think it was, the issue https://github.com/turbot/steampipe-plugin-aws/issues/1576 doesn't have any details at the time of this review comment), listing managed prefix lists is not supported in only that region, so we need to handle that error in this table

**Review by cbruno10 — CHANGES_REQUESTED** [review]
@ParthaI Please see suggestion, thanks!

File: aws/table_aws_ec2_managed_prefix_list.go [hunk 2]
```diff
@@ -22,7 +22,10 @@ func tableAwsEc2ManagedPrefixList(_ context.Context) *plugin.Table {
...
+				// The specified request includes an unsupported operation. For example, you can't stop an instance that's instance store-backed. Or you might be trying to launch an instance type that is not supported by the specified AMI. The returned message provides details of the unsupported operation.
+				// We need to add the 'UnsupportedOperation' error code to the IgnoreErrorCodes function because while the EC2 service is supported in the 'me-south-1' region, listing managed prefix lists is not supported in that region.
```
Comment (cbruno10) [inline aws/table_aws_ec2_managed_prefix_list.go:27]:
```suggestion
				// Ignore the 'UnsupportedOperation' error because while the EC2 service is supported in the 'me-south-1' region, listing managed prefix lists is not in that region
```

Updated suggestion that's a little less wordy and removes unrelated info about what `UnsupportedOperation` could mean in other tables.

**Review by cbruno10 — CHANGES_REQUESTED** [review]
@ParthaI Added another suggestion based on your latest comment, please have a look!

**Review by cbruno10 — APPROVED** [review]
